create table users (id int8 not null,
                    created timestamp,
                    email varchar(255),
                    first_name varchar(255),
                    is_active boolean not null,
                    last_name varchar(255),
                    password varchar(255),
                    phone_number varchar(255),
                    specialization varchar(255),
                    study_format varchar(255),
                    primary key (id));
