#Configured by Chyngyz Sharshekeev at 5pm 20.07.2022

name: peaksoftlms-m1-CICD-Pipeline-to-AWS-ElasticBeanstalk

on:
  push:
    branches:
      - main

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/peaksoftlms-m1.jar

  cd_part:
    runs-on: ubuntu-latest
    needs  : [ci_part]

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          use_existing_version_if_available: false
          application_name: peaksoftlms
          environment_name: Peaksoftlms-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: peaksoftlms-m1.jar