name: Java CI with Maven

on:
  push:
    branches:
       - main

jobs:

  ci_part:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.2'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          description: 'AWS Session Token when using temporary security credentials such as when assuming a role in AWS through STS'
          required: false
          application_name: peaksoftlms
          environment_name: Peaksoftlms-env
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: target/peaksoftlms-m1.jar